In [23]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import roc_auc_score, accuracy_score, classification_report,confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import xgboost as xgb

# New Section

In [2]:
data = pd.read_csv('/content/creditcard.csv')

In [ ]:
data.head()


Time        V1        V2        V3        V4        V5        V6        V7  \
0     0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1     0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2     1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3     1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4     2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62    0.0  
1  0.125895 -0.008983  0.014724    2.69    0.0  
2 -0.139097 -0.055353 -0.059752  378.66    0.0  
3 -0.221929  0.062723  0.061458  123.50    0.0  
4  0.502292  0.219422  0.215153   69.99    0.0  

[5 rows x 31 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17918 entries, 0 to 17917
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Time    17918 non-null  int64  
 1   V1      17918 non-null  float64
 2   V2      17918 non-null  float64
 3   V3      17918 non-null  float64
 4   V4      17918 non-null  float64
 5   V5      17917 non-null  float64
 6   V6      17917 non-null  float64
 7   V7      17917 non-null  float64
 8   V8      17917 non-null  float64
 9   V9      17917 non-null  float64
 10  V10     17917 non-null  float64
 11  V11     17917 non-null  float64
 12  V12     17917 non-null  float64
 13  V13     17917 non-null  float64
 14  V14     17917 non-null  float64
 15  V15     17917 non-null  float64
 16  V16     17917 non-null  float64
 17  V17     17917 non-null  float64
 18  V18     17917 non-null  float64
 19  V19     17917 non-null  float64
 20  V20     17917 non-null  float64
 21  V21     17917 non-null  float64
 22

In [ ]:
data.shape

(17918, 31)

In [ ]:
data['Class'].value_counts()

Class
0.0    17836
1.0       81
Name: count, dtype: int64

In [ ]:
data.describe()

Time            V1            V2            V3            V4  \
count  17918.000000  17918.000000  17918.000000  17918.000000  17918.000000   
mean   13905.276259     -0.244970      0.258166      0.777804      0.291614   
std     9867.916251      1.893161      1.508296      1.766872      1.479519   
min        0.000000    -30.552380    -40.978852    -31.103685     -5.172595   
25%     3781.250000     -0.959806     -0.305367      0.338327     -0.629972   
50%    12347.500000     -0.306803      0.235061      0.924255      0.230058   
75%    23775.000000      1.164015      0.876538      1.557391      1.155770   
max    29031.000000      1.960497     16.713389      4.101716     11.927512   

                 V5            V6            V7            V8            V9  \
count  17917.000000  17917.000000  17917.000000  17917.000000  17917.000000   
mean      -0.146329      0.099878     -0.150970      0.012969      0.734707   
std        1.423917      1.327756      1.342027      1.318460      1.273597   
min      -32.092129    -23.496714    -26.548144    -23.632502     -7.175097   
25%       -0.729796     -0.651820     -0.599770     -0.175261     -0.102798   
50%       -0.192681     -0.169764     -0.076457      0.020846      0.726588   
75%        0.347812      0.493661      0.447398      0.272076      1.480254   
max       34.099309     21.393069     34.303177     20.007208     10.392889   

       ...           V21           V22           V23           V24  \
count  ...  17917.000000  17917.000000  17917.000000  17917.000000   
mean   ...     -0.052197     -0.146256     -0.038504      0.014510   
std    ...      0.826158      0.634077      0.526168      0.588938   
min    ...    -11.468435     -8.593642    -26.751119     -2.687773   
25%    ...     -0.262581     -0.556175     -0.173509     -0.330602   
50%    ...     -0.119493     -0.118803     -0.046656      0.063623   
75%    ...      0.041561      0.250886      0.072758      0.398391   
max    ...     22.614889      4.534454     13.876221      3.695503   

                V25           V26           V27           V28        Amount  \
count  17917.000000  17917.000000  17917.000000  17917.000000  17917.000000   
mean       0.119974      0.036454      0.014558      0.007047     67.504000   
std        0.438850      0.537046      0.397673      0.248679    189.184677   
min       -7.495741     -1.338556     -8.567638     -3.575312      0.000000   
25%       -0.140146     -0.345451     -0.071486     -0.011786      5.490000   
50%        0.158356     -0.030200      0.003094      0.018529     15.950000   
75%        0.397765      0.342446      0.098968      0.077345     56.670000   
max        5.525093      3.517346      8.254376      4.860769   7712.430000   

              Class  
count  17917.000000  
mean       0.004521  
std        0.067087  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000  

[8 rows x 31 columns]

In [6]:
legit = data[data.Class == 0]
fraud = data[data.Class == 1]

In [7]:
legit_sample = legit.sample(n=len(fraud), random_state=2)
data = pd.concat([legit_sample, fraud], axis=0)

In [8]:
# Split data into features and target
X = data.drop(columns="Class", axis=1)
y = data["Class"]

In [9]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=2)

In [ ]:
logistic_model = LogisticRegression(max_iter=500)


In [ ]:
logistic_model.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=500)

In [ ]:
logistic_train_pred = logistic_model.predict(X_train)
logistic_test_pred = logistic_model.predict(X_test)

In [ ]:
logistic_train_acc = accuracy_score(y_train, logistic_train_pred) * 100
logistic_test_acc = accuracy_score(y_test, logistic_test_pred) * 100

In [ ]:
logistic_conf_matrix = confusion_matrix(y_test, logistic_test_pred)

In [ ]:
print("Logistic Regression:")
print(f"Train Accuracy: {logistic_train_acc}")
print(f"Test Accuracy: {logistic_test_acc}")
print("Confusion Matrix:")
print(logistic_conf_matrix)


Logistic Regression:
Train Accuracy: 99.2248062015504
Test Accuracy: 90.9090909090909
Confusion Matrix:
[[16  1]
 [ 2 14]]


In [10]:
decision_tree = DecisionTreeClassifier(random_state=2)


In [11]:
decision_tree.fit(X_train, y_train)

DecisionTreeClassifier(random_state=2)

In [12]:
tree_train_pred = decision_tree.predict(X_train)
tree_test_pred = decision_tree.predict(X_test)

In [13]:
tree_train_acc = accuracy_score(y_train, tree_train_pred) * 100
tree_test_acc = accuracy_score(y_test, tree_test_pred) * 100

In [14]:
tree_conf_matrix = confusion_matrix(y_test, tree_test_pred)

In [15]:
y_probs = decision_tree.predict_proba(X_test)[:, 1]

In [16]:
dt_auc = roc_auc_score(y_test, y_probs)
print("Decision Tree AUC:", dt_auc)

Decision Tree AUC: 0.9526209677419355


# New Section

In [17]:
print("Decision Tree:")
print(f"Train Accuracy: {tree_train_acc:.2f}%")
print(f"Test Accuracy: {tree_test_acc:.2f}%")
print("Confusion Matrix:")
print(tree_conf_matrix)

Decision Tree:
Train Accuracy: 100.00%
Test Accuracy: 95.24%
Confusion Matrix:
[[30  2]
 [ 1 30]]


In [ ]:
random_forest = RandomForestClassifier(random_state=2)

In [ ]:
random_forest.fit(X_train, y_train)

RandomForestClassifier(random_state=2)

In [ ]:
forest_train_pred = random_forest.predict(X_train)
forest_test_pred = random_forest.predict(X_test)

In [ ]:
forest_train_acc = accuracy_score(y_train, forest_train_pred) * 100
forest_test_acc = accuracy_score(y_test, forest_test_pred) * 100

In [ ]:
forest_conf_matrix = confusion_matrix(y_test, forest_test_pred)


In [ ]:
print("Random Forest:")
print(f"Train Accuracy: {forest_train_acc:.2f}%")
print(f"Test Accuracy: {forest_test_acc:.2f}%")
print("Confusion Matrix:")
print(forest_conf_matrix)

Random Forest:
Train Accuracy: 100.00%
Test Accuracy: 93.94%
Confusion Matrix:
[[17  0]
 [ 2 14]]


In [ ]:
knn = KNeighborsClassifier()

In [ ]:
knn.fit(X_train, y_train)


KNeighborsClassifier()

In [ ]:
knn_train_pred = knn.predict(X_train)
knn_test_pred = knn.predict(X_test)

In [ ]:
knn_train_acc = accuracy_score(y_train, knn_train_pred) * 100
knn_test_acc = accuracy_score(y_test, knn_test_pred) * 100

In [ ]:
knn_conf_matrix = confusion_matrix(y_test, knn_test_pred)


In [ ]:
print("K-Nearest Neighbors:")
print(f"Train Accuracy: {knn_train_acc:.2f}%")
print(f"Test Accuracy: {knn_test_acc:.2f}%")
print("Confusion Matrix:")
print(knn_conf_matrix)

K-Nearest Neighbors:
Train Accuracy: 75.97%
Test Accuracy: 72.73%
Confusion Matrix:
[[11  6]
 [ 3 13]]


In [ ]:
svm = SVC(kernel='linear', random_state=2)

In [ ]:
svm.fit(X_train, y_train)

SVC(kernel='linear', random_state=2)

In [ ]:
svm_train_pred = svm.predict(X_train)
svm_test_pred = svm.predict(X_test)


In [ ]:
svm_train_acc = accuracy_score(y_train, svm_train_pred) * 100
svm_test_acc = accuracy_score(y_test, svm_test_pred) * 100

In [ ]:
svm_conf_matrix = confusion_matrix(y_test, svm_test_pred)

In [ ]:
print("Support Vector Machine:")
print(f"Train Accuracy: {svm_train_acc:.2f}%")
print(f"Test Accuracy: {svm_test_acc:.2f}%")
print("Confusion Matrix:")
print(svm_conf_matrix)

Support Vector Machine:
Train Accuracy: 99.22%
Test Accuracy: 93.94%
Confusion Matrix:
[[17  0]
 [ 2 14]]


In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Build DNN model
model = Sequential([
    Dense(32, input_dim=X_train.shape[1], activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Train model
history = model.fit(X_train_scaled, y_train, epochs=10, batch_size=32, validation_split=0.2, verbose=1)

# Evaluate model
y_pred = (model.predict(X_test_scaled) > 0.5).astype("int32")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 5s 266ms/step - accuracy: 0.5693 - loss: 0.6388 - val_accuracy: 0.5769 - val_loss: 0.6219
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.6011 - loss: 0.5754 - val_accuracy: 0.6538 - val_loss: 0.5704
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7739 - loss: 0.5223 - val_accuracy: 0.8077 - val_loss: 0.5255
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.8462 - loss: 0.4422 - val_accuracy: 0.8462 - val_loss: 0.4846
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 100ms/step - accuracy: 0.8997 - loss: 0.4132 - val_accuracy: 0.9231 - val_loss: 0.4483
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.9210 - loss: 0.3773 - val_accuracy: 0.9615 - val_loss: 0.4181
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - accuracy: 0.9200 - loss: 0.3564 - val_accuracy: 0.9615 - val_loss: 0.3914
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9189 - loss: 0.3229 - val_accuracy: 0.9615 - val_loss: 0.36

In [18]:
model = Sequential()
model.add(Dense(16, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [19]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['AUC'])

# 2. Model train karna
model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=1)

# 3. Prediction probabilities lena
y_probs_keras = model.predict(X_test).ravel()

Epoch 1/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - AUC: 0.4947 - loss: 1018.8741
Epoch 2/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - AUC: 0.4977 - loss: 646.8873  
Epoch 3/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - AUC: 0.5124 - loss: 295.8720 
Epoch 4/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - AUC: 0.4975 - loss: 75.5231 
Epoch 5/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - AUC: 0.4960 - loss: 84.8452 
Epoch 6/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - AUC: 0.5540 - loss: 41.1844 
Epoch 7/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - AUC: 0.6123 - loss: 19.7660
Epoch 8/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - AUC: 0.5567 - loss: 14.5818 
Epoch 9/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - AUC: 0.6982 - loss: 8.6563 
Epoch 10/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - AUC: 0.7694 - loss: 5.1107 
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


In [20]:
keras_auc = roc_auc_score(y_test, y_probs_keras)
print("Keras Model AUC:", keras_auc)

Keras Model AUC: 0.8044354838709677


In [21]:
y_pred_keras = (y_probs_keras >= 0.5).astype(int)
cm_keras = confusion_matrix(y_test, y_pred_keras)
print("Confusion Matrix (Keras):\n", cm_keras)

Confusion Matrix (Keras):
 [[20 12]
 [ 6 25]]


In [24]:
xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss')

# 2. Train karo
xgb_model.fit(X_train, y_train)

# 3. Predict probabilities for AUC
y_probs_xgb = xgb_model.predict_proba(X_test)[:, 1]
xgb_auc = roc_auc_score(y_test, y_probs_xgb)
print("XGBoost AUC:", xgb_auc)

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [16:06:00] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


XGBoost AUC: 0.9868951612903226


In [25]:
# 4. Predict labels for Confusion Matrix
y_pred_xgb = xgb_model.predict(X_test)
cm_xgb = confusion_matrix(y_test, y_pred_xgb)
print("Confusion Matrix (XGBoost):\n", cm_xgb)

Confusion Matrix (XGBoost):
 [[32  0]
 [ 1 30]]
